name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.2"

      - name: Install dependencies
        run: opam install angstrom yojson re async core msgpck ppx_jane ounit2 qcheck-core --yes

      - name: Run tests
        run: opam exec -- dune build @test/runtest
